[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/bonds"]

[programs.localnet]
bonds = "2PAZiQGBhxQx45UsEcjn9iufTXZgrTD1q9ZdNBVR6YEc"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"
