[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/bonds"]

[programs.localnet]
bonds = "DojjMwd2tErELy9vuLs7Jb6JW7FBJEh4f25wibHp3HCm"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000"
